### ISSUE TITLE
关于私钥

### ISSUE THREAD

**Issue by xhlove** [T3rry7f/WVClient#1]
文件里面用到的private_key似乎和widevine-l3-decryptor之前用的不是一个，不知道大佬能不能分享一下具体提取的方法？

**Comment by T3rry7f** [comment]
> 文件里面用到的private_key似乎和widevine-l3-decryptor之前用的不是一个，不知道大佬能不能分享一下具体提取的方法？

是同一个 白盒RSA我也搞不定

**Comment by xhlove** [comment]
好吧蟹蟹回复^_^
