### ISSUE TITLE
license_proxy_address

### ISSUE THREAD

**Issue by nunsie** [T3rry7f/WVClient#2]
Hi, where can i find this proxy server?

**Comment by T3rry7f** [comment]
> Hi, where can i find this proxy server?

It's just a cmd dll loader , i hava uploaded.

**Comment by astrid79** [comment]
Hi @T3rry7f Could you write a small explanation about how this works in the readme.
Although the DLL file is in the same directory, it still didn't work, 
I'm trying with python3.6 btw

**Comment by nyuszika7h** [comment]
@astrid79 Looks like it needs Python 2.

**Comment by nunsie** [comment]
thanks @T3rry7f got it running and script calling it, however OnRejectPromise seems to be firing, see below. Any specific version of the cdm this is meant to work with?

<img width="361" alt="Screenshot 2020-11-05 at 13 50 21" src="https://user-images.githubusercontent.com/6902345/98237751-112da600-1f6e-11eb-976c-7812239a55cf.png">

if not what method is invoked in cdm? i can look into writing my own proxy.

**Comment by T3rry7f** [comment]
> thanks @T3rry7f got it running and script calling it, however OnRejectPromise seems to be firing, see below. Any specific version of the cdm this is meant to work with?
> 
> <img alt="Screenshot 2020-11-05 at 13 50 21" width="361" src="https://user-images.githubusercontent.com/6902345/98237751-112da600-1f6e-11eb-976c-7812239a55cf.png">
> 
> if not what method is invoked in cdm? i can look into writing my own proxy.

Try the new debug version

**Comment by nyuszika7h** [comment]
That one works, just needs some DLLs.

https://www.dll-files.com/ucrtbased.dll.html
https://www.dll-files.com/vcruntime140d.dll.html

**Comment by astrid79** [comment]
is it possible to adapt this for python3 ?

**Comment by nunsie** [comment]
🤘 awesome. Thanks for the amazing work @T3rry7f
